### ISSUE TITLE
licensie

### ISSUE THREAD

**Issue by muhammadarif1** [kollerlukas/TODOList-Android-App#4]

**Comment by IzzySoft** [comment]
@kollerlukas he's right: could you please specify which license you're using for this project?

**Comment by kollerlukas** [comment]
https://github.com/kollerlukas/TODOList-Android-App/commit/6b80fd927043dcc08ae22624fae654f4f9b5d346

**Comment by IzzySoft** [comment]
Thanks Lukas!
